Search.appendIndex(
    [
                {
            "fqsen": "\\Calculadora",
            "name": "Calculadora",
            "summary": "Esta\u0020clase\u0020contiene\u0020funciones\u0020para\u0020realizar\u0020operaciones\u0020aritm\u00E9ticas\u0020b\u00E1sicas.",
            "url": "classes/Calculadora.html"
        },                {
            "fqsen": "\\Calculadora\u003A\u003Asumar\u0028\u0029",
            "name": "sumar",
            "summary": "Suma\u0020dos\u0020n\u00FAmeros.",
            "url": "classes/Calculadora.html#method_sumar"
        },                {
            "fqsen": "\\Calculadora\u003A\u003Arestar\u0028\u0029",
            "name": "restar",
            "summary": "Resta\u0020dos\u0020n\u00FAmeros.",
            "url": "classes/Calculadora.html#method_restar"
        },                {
            "fqsen": "\\Calculadora\u003A\u003Amultiplicar\u0028\u0029",
            "name": "multiplicar",
            "summary": "Multiplica\u0020dos\u0020n\u00FAmeros.",
            "url": "classes/Calculadora.html#method_multiplicar"
        },                {
            "fqsen": "\\Calculadora\u003A\u003Adividir\u0028\u0029",
            "name": "dividir",
            "summary": "Divide\u0020dos\u0020n\u00FAmeros.",
            "url": "classes/Calculadora.html#method_dividir"
        },                {
            "fqsen": "\\sumar\u0028\u0029",
            "name": "sumar",
            "summary": "Suma\u0020dos\u0020n\u00FAmeros.",
            "url": "namespaces/default.html#function_sumar"
        },                {
            "fqsen": "\\restar\u0028\u0029",
            "name": "restar",
            "summary": "Resta\u0020dos\u0020n\u00FAmeros.",
            "url": "namespaces/default.html#function_restar"
        },                {
            "fqsen": "\\multiplicar\u0028\u0029",
            "name": "multiplicar",
            "summary": "Multiplica\u0020dos\u0020n\u00FAmeros.",
            "url": "namespaces/default.html#function_multiplicar"
        },                {
            "fqsen": "\\dividir\u0028\u0029",
            "name": "dividir",
            "summary": "Divide\u0020dos\u0020n\u00FAmeros.",
            "url": "namespaces/default.html#function_dividir"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
